# -*- coding: utf-8 -*-
"""tarea_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKB-lDl3Gz0dozujwdzE_PfXrGzyEcoi
"""

class Articulo:
    def __init__(self, nombre, precio):
        self.nombre = nombre
        self.precio = precio

    def set_nombre(self, nombre):
        self.nombre = nombre

    def set_precio(self, precio):
        self.precio = precio

    def get_nombre(self):
        return self.nombre

    def get_precio(self):
        return self.precio

    def calculo_iva(self):
        return self.precio


class Granos(Articulo):
    def __init__(self, nombre, precio):
        super().__init__(nombre, precio)
        self.iva = 0

    def set_iva(self, iva):
        self.iva = iva

    def get_iva(self):
        return self.iva

    def calculo_iva(self):
        return super().calculo_iva()


class Harinas(Articulo):
    def __init__(self, nombre, precio):
        super().__init__(nombre, precio)
        self.iva = 5

    def set_iva(self, iva):
        self.iva = iva

    def get_iva(self):
        return self.iva

    def calculo_iva(self):
        return self.precio / (1 + self.iva / 100)


class Condimentos(Articulo):
    def __init__(self, nombre, precio):
        super().__init__(nombre, precio)
        self.iva = 19

    def set_iva(self, iva):
        self.iva = iva

    def get_iva(self):
        return self.iva

    def calculo_iva(self):
        return self.precio / (1 + self.iva / 100)


def main():
    producto1 = Granos("Arroz", 4500)
    producto2 = Harinas("Harina de maíz", 5000)
    producto3 = Condimentos("Sal", 2500)

    print(f"IVA Arroz: {round(producto1.calculo_iva(),2)}")
    print(f"IVA Harina de maíz: {round(producto2.calculo_iva(),2)}")
    print(f"IVA Sal: {round(producto3.calculo_iva(),2)}")


if __name__ == "__main__":
    main()