# -*- coding: utf-8 -*-
"""punto2_tarea9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vpkN_JmfVhlFoIhNk4oLtr8DOKH3y_Lh
"""

# punto 2
from random import randint as r

def encontrar(lista):
    if len(lista) == 1:
        return lista[0]
    mayor = lista[0]
    for i in lista:
        if i > mayor:
            mayor = i
    return mayor

def main():
    Lista = [r(1, 30) for _ in range(15)]
    print("Lista:", Lista)
    maximo_lista = encontrar(Lista)
    print("El numero maximo es:", maximo_lista)

if __name__ == "__main__":
    main()