# -*- coding: utf-8 -*-
"""Punto1_Tarea9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nAx9w_-FJxebD3oS4CZyn3fWDylX8WCD
"""

# punto 1

from random import randint as r

def crear_matriz():
    matriz = []
    for i in range(5):
        matriz.append([])
        for j in range(10):
            num = r(1, 50)
            matriz[i].append(num)
    return matriz

def imprimir(matriz):
    for fila in matriz:
        print(fila)

def max_min(matriz):
    menor = mayor = matriz[0][0]
    posc_mayor = (0, 0)
    posc_menor = (0, 0)

    for i, fila in enumerate(matriz):
        for j, numero in enumerate(fila):
            if numero < menor:
                menor = numero
                posc_menor = (i, j)
            elif numero > mayor:
                mayor = numero
                posc_mayor = (i, j)

    print(f"\nEl número mayor de la  matriz es {mayor} y esta en la posición {posc_mayor}\n")
    print(f"El número menor de  la matriz es {menor} y esta en la posición {posc_menor}")


def matriz_ordenada(matriz):
 for fila in matriz:
        print(fila)

def ordenar_matriz(matriz):
    filas = len(matriz)
    columnas = len(matriz[0])

    for i in range(filas):
        for j in range(columnas):
            max_fila = i
            max_columna = j


            for x in range(i, filas):
                for y in range(j, columnas):
                    if matriz[x][y] > matriz[max_fila][max_columna]:
                        max_fila = x
                        max_columna = y


            matriz[i][j], matriz[max_fila][max_columna] = matriz[max_fila][max_columna], matriz[i][j]


def main():
    matriz = crear_matriz()
    print("Matriz original:")
    imprimir(matriz)
    max_min(matriz)
    ordenar_matriz(matriz)

    print("\nMatriz ordenada de mayor a menor:")
    imprimir(matriz)

if __name__ == "__main__":
    main()

