# -*- coding: utf-8 -*-
"""tarea10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190oJKS8DQQJZ3yQ_zLefLu0aDoIbyIZs
"""



def iva(producto, neto, porcentaje_iva):
    valor_iva = (neto * porcentaje_iva) / 100
    base = neto - valor_iva
    return base, valor_iva

def canasta(producto, neto):
    alimentos = {
        'cero_porciento': ['Arroz', 'pan', 'otros productos de panaderia', 'papa', 'yuca', 'otros tuberculos', 'platano',
                            'cebolla', 'tomate', 'zanahoria', 'revuelto verde', 'Otras hortalizas y legumbres frescas',
                            'Frijol', 'Arveja', 'Otras hortalizas y legumbres secas', 'naranjas', 'bananos',
                            'tomate de arbol', 'Moras', 'Otras frutas frescas', 'Res', 'Cerdo', 'Pollo',
                            'Pescado de mar rio y enlatado', 'Huevos', 'Leche', 'Queso', 'Panela', 'Sal', 'Agua',
                            'Almuerzo', 'Hamburguesa', 'Comidas rapidas calientes', 'Gastos de cafeteria',
                            'Comidas rapidas frias'],
        'cinco_porciento': ['Harina de maiz y otras harinas', 'Pastas alimenticias', 'Otros cereales',
                            'Carnes frias y embutidos', 'Azucar', 'Cafe', 'Chocolate'],
        'diecinueve_porciento': ['Cereales preparados', 'Hortalizas y legumbres enlatadas',
                                 'Frutas en conserva o secas', 'Otros productos de mar', 'Otros derivados lacteos',
                                 'Aceites', 'Grasas', 'Otros condimentos', 'Sopas y cremas', 'Salsas y aderezos',
                                 'Dulces confites y gelatinas', 'Otros abarrotes']}
    if producto in alimentos['cero_porciento']:
        return neto
    elif producto in alimentos['cinco_porciento']:
        return iva(producto, neto, 5)
    elif producto in alimentos['diecinueve_porciento']:
        return iva(producto, neto, 19)
    else:
        return 'Error, intente nuevamente'

def main():
    while True:
        producto = input('Ingrese el nombre del producto o si desea finalizar (escriba la palabra "salir"): ')
        if producto.lower() == 'salir':
            break

        neto = float(input('Ingrese el valor neto del producto: '))

        resultado = canasta(producto, neto)

        if isinstance(resultado, tuple):
            print(f'Valor Base: {round(base, 2)}')
            print(f'Valor IVA: {round(valor_iva, 2)}\n')
        else:
            print(resultado)

if __name__ == "__main__":
    main()